language: python
branches:
  only:
  - master
install:
- pip install -r requirements.txt
# before_script:
# - pelican-themes -i ./theme/Just-Read
script:
- make publish s3_upload
env:
  global:
  - secure: JKemPvMcIJ+8dzcC9a0m5e313y5rB+RimyYnUzJ3mEehveMYdo4ngIDyHbd+aormvRK0Z/Lmv+YsnO9gxw0kjgxXXuyMeLPI8Z5YIbJt77MklZlhNTpOseL2fTx3hVJwcR7ov48etaGWUuhV6yJu98oh59UiLTNuiijoQqgitGg/83QVBXuMxYM1C1MxyUezgeg4VjzS+Levr1yi+4av+MDp8NDHWgpJQZC22C0EgcHBqFa4g/ofvu9A/oKhvYaqqkwVK3VxkmGVAtM4K7AHDGtRXjm0w2yKxq3IdxIC/t4SZYdghXhM0rrPBZ0C9wHUZzRMSMxt6njbqHRZjvLoFnxu3NyOmke5gpNzDwi/VzbDS/caUMFBa56FT8h58pJS+TrMNHv+RnEUUYK5La8oak9M4+tTd9x2mCjb5+kQWrmmXjn55tagmZZoMkPpJXBDZ1lx4aphOyPtp7EqNcrg0DmkEBd+gVfegWdH0XEk6JwAUMj+/BjZkRjLICxaU77ZZ7DJEzvA/AlCYpOLGT0o0UXXCL/xGnvuaJmAL4o3qf3DyE2gU7BKarCALhwHFNUmC0s6RO4eJ0QGkxeFXlGM3JHHxg99oQTPT536/xIIquT6iUNqQGSGbu8Byg/uRCsBWcDtUTESDjDZyyTHWvxp4Yng/XuskrIr9Tzj7VQQJJE=
  - secure: quy7Gi+zzsCpoSunZF+/FrBT15qc64Ec+uhCfNjAaymXIGzG9cyVUsV63aBycvp0lela8JT18WQV51dhjknvBVErZXgAORYxJONZn5XritY+9YAj4U4g3ycJqDCzwWw9mZ/S7YkoKUUn8/9PzF57qinRpe1UjDhjP6CNHQLpIfVFgEUBqEE5BkBCZE9vx7CVDLV46vI3nb6jL2CkB8u3Mhr5DzGKfr247+VwTaEWSGCuKV/IAoVLOTSubuW3bt00YSr7Q2GM5FtSEP85N+bLsxGSdV2rQW3db7riE6el+KOxNgSrkQQAa+akEkFrYYfm3iSl4jAblSPZNQA1VTVawon+xnk+PvYmKnQkOXf1rz3bd6bUWLmfiqHjut+SwkpGyd/EdqrcSilsgwVvT3jFFlvfP/nTJkKtX5gj6TM1G2ZSalCcZph/xWblBY4wS6TNxWCCnQscUqKjLsmlV+stRErnj17kL20VGvTfKVnEYg30CkOqzyNKRVpXOm/qbZSeltSm2WMWfvkALzqat84sY8hLJM9C0cDbfmRSbcQrojcXiqgCnnYQ03cjHbd7VIAvkQiRwdlxYKQejOr8S7Ny6S3zvFadw+XikZCClLgASZOfMj2xEU7+AKqKVPuzKQIAkqtmapYUiqosS6GQriaLf6MvuLE02Lpm4YUCGE3al80=
