language: python
branches:
  only:
  - master
addons:
  apt:
    packages:
      - s3cmd

install:
  - pip install -r requirements.txt
  - git clone https://github.com/getpelican/pelican-plugins
before_script:
  - ./setup-s3-cmd
script:
  - make publish s3_upload
env:
  global:
  - secure: su9e6nJR3cOtuCKdET5CPxoahEgw0aOG96L9/8Ns2breUahiwgzZLD1TPOG/xu7Gy4wxQ80ltLtAq9njrqod3UWeqyOvZcW5UMOGWN/x5paInB/2EiZfvJcO8HeB5u857D7b2WVFDFxVXPvbyDv+zEJ31QeaEXvNwf5vetsCqmVWUkfYlRR265PLkwa4j2M9QhSbhOfCMKsdFoRR9pErr3EvMqr8K8sP/fyGVjaL9uX4fuBEbByW4G2HmBr1WSQiMKsmqg6ZsbDUuDGj1TpFB0KBwwpEIojK3tF8ieTN5HOkICPmTEvF4dDSuuI06KE4QRcsKSCoLOBQtJn5V0x+ysBmAJbiJXbvHQLdtFJV24yVbcQjDQBpkgUzSsiXzF2hxmxJlWvLRdrWZ1Pq4/h99gxu0LMH6oTunHSQyqFMX8rubpHDStxYkq0cgsJ7PmHTI0kXGydD+kZ7r3hnhCVSyflVupTkP4a8xbrU6sMuUP0SkZjv0cZZcyC8pImGfTZm3Xt+1+Md/otGgYdFI6W0nFcp+/L0n/1OyLivSx8XTR5yCB/ee0okknyUgfpzGrvmit2+VklPXJEOQSWeTidnAstjGAhnneugpqran5p2Fof6p+hLNxPh/HnXBnLw3mXLCG5NBI/ZF53piiIOuiuISc/+jofJQ7WDjZlyr0OiS6c=
  - secure: rDuUysbkCqBdiJv95ZxnP1ej9cNOB9F5LXkzuC/5lAUd7sGWuqzxPBEGg0uKac5vHzLe6gEGR581/eaBHDC+Af95qQE2Yfk/VQV51zdZ7iMeqLA4JTqW9uSoa4JZVVM5NCDOjw1wa3dBrt+StIO0Kb1Qf0aLBWzk36WYS/bPt8OxROR7EZAg1GFI/v9LktPYpM/JQTKIOAHU6RrcM1990QW7AKX0U0X/P4WkHq/J7l5uU/hkuqoiN3ULylodQV1eTxakUaEeXcIO3Tr8b3MCwXXurzTtNWkWuL6vOvRpDd07qVSFfDOXAnobMW3cLsqoCASe790n464oAwQMytgJZq1kZhtZxubfdtCV6rFYz8cbWp3ZEfPhdKXDbLJ4PwSApNlwQuw08O7mNeHMR/23XejoLYxUSGSbtq54zE9zzO3PmF6LE89zkP49ICqCuMSG82Mo2seEos2wksk1+22JibooSZujkXqNkGkVhMaXdERFMk7+dWOW/KURIDeMGRXb7fNHksunMGvpt4UMAA1KvqFNXLom4mjI5K5ulRK1TvJD6G8ERvTO11e/r2ZtAOVpkyBaGtNjiyYkLWFE5W0kw2YPpxerg0TZsTPKHy2TCIxyyIYez+ZBp2wzAB2KUCv4xAZ85eMjl6otnTEGN1LiKM/QsPPH1VXwGYDJLE5j0E0=
