---
name: "Blog"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "15"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pip-tools
          pip-sync requirements.txt
          npm install
          echo "$GITHUB_WORKSPACE/node_modules/.bin" >> $GITHUB_PATH

      - name: Assert that our dependencies are reachable
        run: |
          echo $PATH
          python --version
          pelican --version
          sass --version

      - name: Clone plugins
        run: git clone https://github.com/getpelican/pelican-plugins

      - name: Build the page
        run: inv site

      - name: Publish the content
        run: inv upload

      - name: Invalidate the existing distribution
        run: inv invalidate
